### ISSUE TITLE
Cannot find module 'get-it/lib-node'

### ISSUE THREAD

**Issue by Kelsay** [sanity-io/get-it#16]
The module is required by @sanity/client

Using npm 6.4.1 and Brunch 2.10.17.
Npm compiles the module creating two folders 'lib' and 'lib-node'. However, main entry file index.js points just to './lib-node'

`module.exports = require('./lib-node')`

This causes module to fail in browser context, where only '/lib' is bundled. However, everything works just fine when manually changed to:

`module.exports = require('./lib')`

Is this a problem with module or more probably with bundler?

**Comment by rexxars** [comment]
Which bundler are you using?

**Comment by rexxars** [comment]
Oh, brunch eh? We use the browser field quite extensively to be able to bundle different things for the browser and node. Brunch may not fully support it, I suppose?
